import { useState } from "react";
import { ArrowLeft, FileText, X, ChevronRight } from "lucide-react";
import { Link } from "wouter";

const DOCS = [
  {
    id: "tos",
    title: "Terms of Service",
    updated: "January 15, 2026",
    content: `TERMS OF SERVICE

Last updated: January 15, 2026

Welcome to KOHO Financial Inc. ("KOHO", "we", "us", or "our"). By using the KOHO app and services, you agree to these Terms of Service. Please read them carefully.

1. ACCOUNT ELIGIBILITY
To open a KOHO account, you must be a Canadian resident, at least 18 years of age, and provide accurate personal information during registration.

2. ACCOUNT SECURITY
You are responsible for maintaining the confidentiality of your login credentials. Notify KOHO immediately at support@koho.ca if you suspect unauthorized access to your account.

3. SPENDING AND LOAD LIMITS
Account velocity limits apply to all transactions. You can view your current limits in the Account Settings section of the app. KOHO reserves the right to adjust these limits at any time.

4. FEES
Certain KOHO plans and add-on features may carry monthly or transaction fees. All applicable fees are disclosed at the time of purchase and in your monthly statements.

5. CASHBACK AND REWARDS
Cashback is calculated based on eligible purchases made with your KOHO card. KOHO reserves the right to modify cashback rates and eligible categories at any time with reasonable notice.

6. TERMINATION
Either party may close the account at any time. Remaining balances will be returned to you within 10 business days of account closure.

7. GOVERNING LAW
These Terms are governed by the laws of the Province of British Columbia and the federal laws of Canada.

8. CONTACT
KOHO Financial Inc.
601 West Broadway, Suite 400
Vancouver, BC V5Z 4C2
support@koho.ca`,
  },
  {
    id: "privacy",
    title: "Privacy Policy",
    updated: "February 3, 2026",
    content: `PRIVACY POLICY

Last updated: February 3, 2026

KOHO Financial Inc. is committed to protecting your personal information. This Privacy Policy describes how we collect, use, and disclose your information.

1. INFORMATION WE COLLECT
We collect information you provide directly (name, email, SIN, date of birth), information generated by your use of our services (transactions, spending patterns), and technical information (device type, IP address, app usage).

2. HOW WE USE YOUR INFORMATION
We use your information to provide and improve our services, verify your identity, process transactions, communicate with you about your account, detect and prevent fraud, and comply with legal obligations.

3. SHARING YOUR INFORMATION
We do not sell your personal information. We may share information with service providers acting on our behalf, financial institutions required to process your transactions, and regulatory authorities as required by law.

4. DATA RETENTION
We retain your personal information for as long as your account is active and for a period afterward as required by law, typically seven years.

5. YOUR RIGHTS
You have the right to access, correct, or request deletion of your personal information. Contact privacy@koho.ca with any requests.

6. SECURITY
We use industry-standard encryption and security measures to protect your information. However, no method of transmission over the internet is 100% secure.

7. COOKIES
The KOHO app uses analytics tools to improve user experience. You can opt out of analytics in your device settings.

8. CONTACT
privacy@koho.ca`,
  },
  {
    id: "cardholder",
    title: "Cardholder Agreement",
    updated: "December 1, 2025",
    content: `CARDHOLDER AGREEMENT

Last updated: December 1, 2025

This Cardholder Agreement governs the use of your KOHO Prepaid Mastercard issued by Peoples Trust Company under licence from Mastercard International.

1. CARD ISSUANCE
Your KOHO card is a prepaid, reloadable Mastercard. It is not a credit card and does not provide access to credit.

2. LOADING FUNDS
You may load funds via Interac e-Transfer, bank transfer, or direct deposit. A maximum balance of $20,000 applies at all times.

3. USING YOUR CARD
Your card can be used anywhere Mastercard is accepted worldwide, subject to your account velocity limits. Certain transaction types (gambling, adult content) are restricted.

4. FEES
Refer to the KOHO fee schedule available in the app under Account Settings > Documents for a complete list of applicable fees.

5. LOST OR STOLEN CARDS
Report lost or stolen cards immediately through the app (Cards > Report lost/stolen) or by calling 1-855-564-6999. You will not be liable for unauthorized transactions reported promptly.

6. DISPUTE RESOLUTION
To dispute a transaction, navigate to the transaction in your app and select "Dispute". You must dispute within 60 days of the transaction date.

7. EXPIRY
Your card expires on the date shown on the card face. Funds on an expired card will be returned to you upon request.

8. MASTERCARD ZERO LIABILITY
As a Mastercard cardholder, you benefit from Mastercard's Zero Liability policy, protecting you from unauthorized purchases.`,
  },
];

export default function LegalDocs() {
  const [openDoc, setOpenDoc] = useState<(typeof DOCS)[0] | null>(null);

  return (
    <div className="h-full overflow-y-auto bg-gray-50 flex flex-col pb-24">
      <header className="flex items-center px-4 py-4 border-b border-gray-100 bg-white sticky top-0 z-10">
        <Link href="/profile" className="p-1 rounded-full hover:bg-gray-100 mr-3">
          <ArrowLeft className="w-5 h-5 text-gray-800" />
        </Link>
        <h1 className="text-base font-bold text-gray-900">Legal Documents</h1>
      </header>

      <div className="px-4 pt-6">
        <p className="text-sm text-gray-500 mb-5 px-1">
          Review the legal documents that govern your KOHO account and services.
        </p>

        <div className="bg-white rounded-3xl shadow-sm border border-gray-100 overflow-hidden divide-y divide-gray-50">
          {DOCS.map(doc => (
            <button
              key={doc.id}
              onClick={() => setOpenDoc(doc)}
              className="w-full flex items-center gap-4 px-5 py-4 hover:bg-gray-50 transition-colors text-left"
            >
              <div className="w-11 h-11 rounded-2xl bg-purple-100 flex items-center justify-center flex-shrink-0">
                <FileText className="w-5 h-5 text-purple-700" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="font-semibold text-gray-900">{doc.title}</p>
                <p className="text-xs text-gray-400 mt-0.5">Updated {doc.updated}</p>
              </div>
              <ChevronRight className="w-5 h-5 text-gray-400 flex-shrink-0" />
            </button>
          ))}
        </div>
      </div>

      {/* Full-text viewer */}
      {openDoc && (
        <div className="fixed inset-0 z-50 bg-white flex flex-col">
          <header className="flex items-center justify-between px-4 py-4 border-b border-gray-100 flex-shrink-0">
            <button onClick={() => setOpenDoc(null)} className="p-1 rounded-full hover:bg-gray-100">
              <X className="w-5 h-5 text-gray-800" />
            </button>
            <h2 className="text-sm font-bold text-gray-900 max-w-[200px] truncate">{openDoc.title}</h2>
            <div className="w-7" />
          </header>
          <div className="flex-1 overflow-y-auto px-5 py-4 pb-10">
            <p className="text-xs text-gray-400 mb-4">Last updated: {openDoc.updated}</p>
            <pre className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap font-sans">
              {openDoc.content}
            </pre>
          </div>
        </div>
      )}
    </div>
  );
}
